name: Run

on:
  workflow_dispatch:
    inputs:
      ipa:
        description: "Direct URL to IPA file"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Resign with entitlements
        run: |
          curl -L -o ${{ github.workspace }}/ldid https://github.com/permasigner/ldid/releases/latest/download/ldid_linux_x86_64
          chmod +x ${{ github.workspace }}/ldid
          
          curl -L -o ${{ github.workspace }}/app.ipa "${{ github.event.inputs.ipa }}"
          mkdir -p ${{ github.workspace }}/ipa
          cd ${{ github.workspace }}/ipa
          unzip ${{ github.workspace }}/app.ipa -d .
          cd -

          ${{ github.workspace }}/ldid -S${{ github.workspace }}/ents.plist -M ${{ github.workspace }}/ipa/Payload/*
          
          cd ${{ github.workspace }}/ipa
          zip -r ${{ github.workspace }}/App.ipa .

      - name: Upload IPA
        uses: actions/upload-artifact@v3.1.0
        with:
          name: App
          path: ${{ github.workspace }}/App.ipa
